apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-stage-build-go-sample-miek
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-stage-build-go-sample-miek
    app.kubernetes.io/part-of: test-app-nqli
  name: multi-stage-build-go-sampjnv8
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: multi-stage-build-go-sample-miek
    weight: null
status: {}
