apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-stage-build-go-sample-miek
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-stage-build-go-sample-miek
    app.kubernetes.io/part-of: test-app-nqli
  name: multi-stage-build-go-sample-miek
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-stage-build-go-sample-miek
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-stage-build-go-sample-miek
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-ewyu-tenant/test-app-nqli/multi-stage-build-go-sample-miek@sha256:85d89a8e3d9fce58138c2bc29d38cc1d96faf552d9e542de4d7459f526d56dba
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
